# Pooling 
### なぜやる必要があるのか
- 主にCNNにおいて次元を削減のため

### CNNの層を重ねるのとの違いは何なのか
- 調査中

### どんな方法があるのか
- Global Average Pooling
- Global Max Pooling

In [28]:
import torch

In [35]:
x = torch.rand(1, 4, 4, dtype=torch.float32)
x

tensor([[[0.2065, 0.0621, 0.4763, 0.9794],
         [0.4384, 0.2364, 0.6401, 0.9689],
         [0.6370, 0.9824, 0.2993, 0.5632],
         [0.6052, 0.1257, 0.2201, 0.5400]]])

In [34]:
import torch.nn.functional as F
_x = F.max_pool2d(x, kernel_size=2)
_x

tensor([[[0.5851, 0.8763],
         [0.7630, 0.4385]]])

In [36]:
_x = F.avg_pool2d(x, kernel_size=2)
_x

tensor([[[0.2358, 0.7662],
         [0.5876, 0.4056]]])